groups/urls.py
from django.urls import path
from . import  views


app_name='groups'
urlpatterns=[
    path('',views.ListGroups.as_view(),name='all'),
    path('new/',views.CreateGroup.as_view(),name='create'),
    path('posts/in/<slug:slug>',views.SingleGroup.as_view(),name='single'),
    path('join/<slug:slug>',views.JoinGroup.as_view(),name='join'),
    path('leave/<slug:slug>',views.LeaveGroup.as_view(),name='leave'),


]

posts/urls.py
from django.urls import path
from . import views

app_name='posts'

urlpatterns=[
    path('',views.PostList.as_view(),name='all'),
    path('posts/new',views.CreatePost.as_view(),name='create'),
    path('by/<str:username>',views.UserPosts.as_view(),name='for_user'),
    path('by/<username>/<int:pk>',views.PostDetail.as_view(),name='single'),
    path('delete/<int:pk>',views.DeletePost.as_view(),name='delete'),
]

social/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
# Django provides views that handle login, logout and password reset.
#         We can enable these views by including django.contrib.auth.urls in the URLconf of our project.
    path('accounts/',include('django.contrib.auth.urls')),
# LOGIN_REDIRECT_URL='test' # LOGOUT_REDIRECT_URL ='thanks' : set up in settings.py
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('groups/',include('groups.urls')),
    path('posts/',include('posts.urls')),
]

groups/models.py
from django.db import models
from django.utils.text import slugify
# slugify:    Convert to ASCII if 'allow_unicode' is False. Convert spaces to hyphens.
#     Remove characters that aren't alphanumerics, underscores, or hyphens.
#     Convert to lowercase. Also strip leading and trailing whitespace.
from social import settings
# Create your models here.
import misaka
#misaka maintains structure of description text added....for example refer groups/test.py
from django.urls import  reverse


from django.contrib.auth import  get_user_model
User=get_user_model()



from django import template
register=template.Library()

class Group(models.Model):
    name=models.CharField(max_length=255,unique=True)
    slug=models.SlugField(allow_unicode=True,unique=True)
    description=models.TextField(blank=True,default='')
    description_html=models.TextField(editable=True,default='',blank=True)
    #Field.editable : If False, the field will not be displayed in the admin or any other ModelForm.
    # They are also skipped during model validation. Default is True.
    members=models.ManyToManyField(settings.AUTH_USER_MODEL,through='GroupMember')
    # members=models.ManyToManyField(User,through='GroupMember')


    def __str__(self):
        return self.name
    #A classic use-case for overriding the built-in methods is if you want
    #  something to happen whenever you save an object. For example (see save()
    def save(self,*args,**kwargs):
        self.slug=slugify(self.name)
        self.description_html=misaka.html(self.description)
        super().save(*args,**kwargs)

#This tells Django how to calculate the URL for an object.
    def get_absolute_url(self):
        return reverse('groups:single',kwargs={'slug':self.slug})

    class Meta:
        ordering=['name']

class GroupMember(models.Model):
   group=models.ForeignKey(Group,related_name='memberships',on_delete=models.CASCADE)
   user=models.ForeignKey(settings.AUTH_USER_MODEL,related_name='user',on_delete=models.CASCADE)
   # user=models.ForeignKey(User,related_name='user',on_delete=models.CASCADE)


   def __str__(self):
       return self.user.username


   class Meta:
       unique_together=['group','user']

groups/views.py
from django.shortcuts import render,get_object_or_404
from django.contrib import messages
from django.contrib.auth.mixins import  (LoginRequiredMixin,
                                         PermissionRequiredMixin)
from django.urls import  reverse
from  django.views.generic import (CreateView,DetailView,ListView
                                   ,RedirectView)
from .models import Group,GroupMember
# Create your views here.
from django.contrib.auth import get_user_model
User=get_user_model()

class CreateGroup(LoginRequiredMixin,CreateView):
    fields = ('name','description')
    model = Group
    #CreateView redirects like below
    # """Return the URL to redirect to after processing a valid form."""
    # if self.success_url:
    #     url = self.success_url.format(**self.object.__dict__)
    # else:
    #     try:
    #         url = self.object.get_absolute_url()

class SingleGroup(DetailView):
    model = Group

class ListGroups(ListView):
    model = Group

class JoinGroup(LoginRequiredMixin,RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single',kwargs={'slug':self.kwargs.get('slug')})

#This is a top-level method, and there's one for each HTTP verb - get(), post(), patch(), etc.
    # You would override it when you want to do something before a request is processed by the view, or after.
    def get(self,request,*args,**kwargs):
        group=get_object_or_404(Group,slug=self.kwargs.get('slug'))

        try:
            GroupMember.objects.create(user=self.request.user,group=group)

        except:
            messages.warning(self.request,'You are already a member')
        else:
            messages.success(self.request,'You are a member')

        return super().get(request,*args,**kwargs)# this calles the get method of parent class redirect view


class LeaveGroup(LoginRequiredMixin,RedirectView):
    #class django.views.generic.base.RedirectView¶
# Redirects to a given URL.
#
# The given URL may contain dictionary-style string formatting, which will be interpolated against the
# parameters captured in the URL. Because keyword interpolation is always done (even if no arguments are passed in),
# any "%" characters in the URL must be written as "%%" so that Python will convert them to a single percent sign on output.
    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug': self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        try:
            membership=GroupMember.objects.filter(user=self.request.user,
                                                  group__slug=self.kwargs.get('slug')).get()

        except GroupMember.DoesNotExist:
            messages.warning(self.request,'Sorry you are not a member')

        else:
            membership.delete()
            messages.success(self.request,'You have left the group')

        return  super().get(request,*args,**kwargs)

groups/templates/groups/group_base.html
{% extends 'base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        {% block pregroup %} {% endblock %}
        {% block group_content %} {% endblock %}
        {% block postgroup %} {% endblock %}
    </div>
</div>

{% endblock %}

groups/templates/groups/group_detail.html
{% extends 'groups/group_base.html' %}

{% block pregroup %}
<h1>{{group.name}}</h1>
<br>

<h3 class="mt-5 pr-10"> Member Count: {{group.members.count}}</h3>


<div class=" mt-8">
    {% if user in group.members.all %}

    <a href="{%url 'groups:leave' slug=group.slug %}"
       class="btn btn-lg btn-fill btn-warning">Leave Group</a>

    {% else %}

     <a href="{%url 'groups:join' slug=group.slug %}"
       class="btn btn-lg btn-fill btn-warning">Join Group</a>

    {% endif %}
</div>
{% endblock %}

{% block group_content %}
<div class="col-md-8">
{% if group.posts.count == 0 %}
<h2> No posts in this group </h2>

{% else %}

    {% for post in group.posts.all %}
    {% include 'posts/_post.html' %}
    {% endfor %}

{% endif %}
</div>


{% endblock %}

groups/templates/groups/group_form.html
{% extends 'groups/group_base.html'  %}
{% load bootstrap4 %}

{% block group_content %}
<h2>Create a new group!</h2>
<div class="container">
    <!--action specifies where to send data after form submission-->
<form action="{%url 'groups:create' %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-primary btn-large" value="Create">
</form>
</div>
{% endblock %}

groups/templates/groups/group_list.html
{% extends 'groups/group_base.html' %}

{% block pregroup %}
<div class="col-md-4">
    <div class="content">
        {% if user.is_authenticated %}
        <h2>Welcome Back!
        <a href="{% url 'posts:for_user' username=user.username %}">
            @{{user.username}}
        </a></h2>
        {% endif %}

        <h2> Groups</h2>
        <p>Welcome to groups page!</p>

    </div>
    {%if user.is_authenticated%}
    <a href="{%url 'groups:create'%}" class="btn btn-warning">
        Create New Group
    </a>
    {% endif %}
</div>

{% endblock %}

{% block group_content %}
<div class="col-md-8">
    <div class="list-group">
        {% for group in group_list %}
        <a class="list-group-item" href="{% url 'groups:single' slug=group.slug %}">
            <h3 class="title list-group-item-heading">{{group.name}}</h3>
            <div class="list-group-item-text container-fluid">
                <!--safe removes all html tags and preserves their functionality...like <b></b> will be preserved-->
                {{group.description_html|safe}}
                <div class="row">
                    <div class="col-md-4">
                        <span class="badge">{{group.members.count}}</span>
                        member{{group.members.count|pluralize}}
                    </div>
                    <div class="col-md-4">
                        <span class=badge">{{group.posts.count}}</span>
                         post{{group.posts.count|pluralize}}
                        <!--the pluralise method will by default add 's' that is pluralise the word if count is more than 1-->
                    </div>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
</div>

{% endblock %}