accounts/urls.py
from django.urls import path,include
from django.contrib.auth import views as auth_views
from . import views

app_name='accounts'
urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    #template name is provided becuase by default django will look into 'registration/login.html'.So either proceed
    # above way or below commented and place login.html inside a registration directory prsent within templates directory of
    # accounts app
    # path('login/',auth_views.LoginView.as_view(),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),#logout view has a default view
    path('signup/',views.SignUp.as_view(),name='signup'),
    path('groups/',include('groups.urls')),

]

groups/urls.py
from django.urls import path
from . import  views


app_name='groups'
urlpatterns=[
    path('',views.ListGroups.as_view(),name='all'),
    path('new/',views.CreateGroup.as_view(),name='create'),
    path('posts/in/<slug:slug>',views.SingleGroup.as_view(),name='single'),
    path('join/<slug:slug>',views.JoinGroup.as_view(),name='join'),
    path('leave/<slug:slug>',views.LeaveGroup.as_view(),name='leave'),


]

posts/urls.py
from django.urls import path
from . import views

app_name='posts'

urlpatterns=[
    path('',views.PostList.as_view(),name='all'),
    path('posts/new',views.CreatePost.as_view(),name='create'),
    path('by/<str:username>',views.UserPosts.as_view(),name='for_user'),
    path('by/<username>/<int:pk>',views.PostDetail.as_view(),name='single'),
    path('delete/<int:pk>',views.DeletePost.as_view(),name='delete'),
]

social/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
# Django provides views that handle login, logout and password reset.
#         We can enable these views by including django.contrib.auth.urls in the URLconf of our project.
    path('accounts/',include('django.contrib.auth.urls')),
# LOGIN_REDIRECT_URL='test' # LOGOUT_REDIRECT_URL ='thanks' : set up in settings.py
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('groups/',include('groups.urls')),
    path('posts/',include('posts.urls')),
]

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Star Social</title>
    <!--Bootstrap-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!--js-->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <!--css-->
    <script type ="stylesheet" src="{% static 'social/css/master.css'  %}"></script>
    <!--js-->

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mynav" id="navbar">
  <a class="navbar-brand mynav" href="{% url 'home'%}">Star Social</a>

  <div class="collapse navbar-collapse ml-auto" id="navbarNav">
    <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'posts:create' %}">Posts</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'groups:all' %}">Groups</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'groups:create' %}"> Create Groups</a>
      </li><li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:logout' %}"> LogOut</a>
      </li>
        {% else %}
        <li class="nav-item">
        <a class="nav-link" href="{% url 'groups:all' %}"> Groups </a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:login' %}"> Login </a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:signup' %}"> SignUp</a>
        </li>

     {% endif %}

    </ul>
  </div>
</nav>
<div class="container mt-5 mycontent">
{% block body %}
{% endblock %}
</div>
<canvas id="canvas"></canvas>
</body>
 <script src="{% static 'social/js/master.js' %}" type="text/javascript" ></script>
</html>

templates/index.html
{% extends 'base.html' %}


{% block body %}
<h1>Welcome to Star Social !!</h1>
{% endblock %}

templates/test.html
{% extends 'base.html' %}

{% block body %}
<h1>You are now Logged In</h1>
{% endblock %}

templates/thanks.html
{% extends 'base.html' %}


{% block body %}
<h1>Thanks for visiting!!</h1>

{% endblock %}